Name = "Bull Branch, ME" # Friendly name for the gage
Id = 1 # Gage ID number on server, check with server admin for an ID
Password = "1234" # Password for luggage/uploading data to server for this gage
Location = "Twin Bridges Road, Ketchum, ME" # Full human readable description of the gage
Latitude = 44.5029
Longitude = -70.9147
Elevation = 942
ElevationUnit = "ft"
Cordinates = [44.5029, -70.9147] # Gage location in decimal degrees. Easy to find either using something like Caltopo or a GPS reading when positioning the gage
PowerType = "solar" # Options for power source. If attached to the grid then use 'grid'. If using solar then use 'solar'
BatteryType = "LIon" # Options for the battery to get power levels including 'Lead', 'LIon', 'LiPo' if grid tied use 'no'.
BatteryAIN = "P9_38" # AIN that the battery is connected to.
BatteryVoltage = 3.7 # Nominal battery voltage. Largely used for single/multi cell LIons or LiPos.
PowerCape = "AndiceLabs" # If using a cape for power enter cape type otherwise use 'no'. ["AndiceLabs"]
UpdateInterval = 15 # How often should it try to collect a sample and update the server in minutes
DepthUART = "UART2"
SerialDev = "/dev/ttyO2"
PostURL = "http://192.168.1.222:5000/0.1/gage/1/sample"